services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    ports: 
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ecommerce

